# Generated by Django 5.2.15 on 2026-07-11 13:36

from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User = get_user_model()
    # You can set the password here
    if not User.objects.filter(email='abhaympunathil@gmail.com').exists():
        User.objects.create_superuser(
            email='abhaympunathil@gmail.com',
            full_name='Admin Abhay',
            password='zxcvbnm@2002'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('my_psc_kerala', '0003_userupload'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
