# Generated by Django 5.2.15 on 2026-07-11 13:52

from django.db import migrations
from django.contrib.auth import get_user_model

def create_second_superuser(apps, schema_editor):
    User = get_user_model()
    if not User.objects.filter(email='admin2002@admin.com').exists():
        User.objects.create_superuser(
            email='admin2002@admin.com',
            full_name='Admin',
            password='passw0ed@2002'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('my_psc_kerala', '0004_auto_20260711_1906'),
    ]

    operations = [
        migrations.RunPython(create_second_superuser),
    ]
