# Generated by Django 5.2.15 on 2026-07-11 14:14

from django.db import migrations
from django.contrib.auth import get_user_model

def make_superusers(apps, schema_editor):
    User = get_user_model()
    
    # Force abhaympunathil@gmail.com to be a superuser
    user1, created1 = User.objects.get_or_create(
        email='abhaympunathil@gmail.com',
        defaults={'full_name': 'Admin Abhay'}
    )
    user1.is_staff = True
    user1.is_superuser = True
    user1.is_active = True
    user1.set_password('zxcvbnm@2002')
    user1.save()

    # Force admin2002@admin.com to be a superuser
    user2, created2 = User.objects.get_or_create(
        email='admin2002@admin.com',
        defaults={'full_name': 'Admin'}
    )
    user2.is_staff = True
    user2.is_superuser = True
    user2.is_active = True
    user2.set_password('passw0ed@2002')
    user2.save()


class Migration(migrations.Migration):

    dependencies = [
        ('my_psc_kerala', '0005_auto_20260711_1922'),
    ]

    operations = [
        migrations.RunPython(make_superusers),
    ]
