# Generated by Django 5.2.15 on 2026-07-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_psc_kerala', '0006_auto_20260711_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., KAS Prelims 2020', max_length=255)),
                ('exam_name', models.CharField(help_text='e.g., Kerala Administrative Service', max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('pdf_file', models.FileField(upload_to='previous_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-uploaded_at'],
            },
        ),
    ]
